#Options
#define the parameters for the compartments by changing the options to 'yes' and 'no'
#dr_compartment is set to yes if a DR compartment is required, this will create the compartment and peer it to the primary compartment?
dr_compartment: no
#Setting ha as yes will create a second FDE and SAP Router server in AZ2?
ha_compartment: no
#busaas is set to yes if BUaaS management servers are to be created, please note this requires the correct AMIs to be shared to the subscription in advance
buaas: no
#Setting ha to yes will create a second FDE and SAP Router server in AZ2? for the DR compartment
dr_ha_compartment: no 
#specify the username to be added on provision
username: "ec2-user"
#Key to be used for the provisioned machines, this must exist on the subscription and also the machine the automation is ran from, so it can be used for machine configuration
vm_public_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAgKPo2E32TDYoeSsSJgqEVlShiApVwlcGh5b0PRbb8KVZ0jukdZTV/0Bx0dioTtQ+gLPqF46GS7kChzQH2h8Vtq52unbRDOzyxEa6O1ZT7QMIfPD088k1rm5quqXxsr/r3Id3IcqaxbHgv1N8A1upYqUIfVZ04fVfNjZsqKW3aZ9BxtrFf2jM1jKlTk0OJFFZkGDgPpe3EnbFPWgS/gRsIThTIgu6Ia7DHCQnHErxSjzkl8wf/ZLwrpcgbDyR+Bk3h6YUxx7SsRmshP+e9zm92vwLs0tgjJIvxkqdHB4EyTrMc2fOxtVi9hGj5vr3JY5UGCep1M6YR7V47nkUWAcKLw== AzureDevDR"

#Standard
#the resource group in which the build will reside
st_resource_group: "P4S-Prototype-AutomationDO"
#Name to be given to Customer Primary VPC
st_virtual_network_name: "VNET-ESO4SAP3-azureProto"
#region for the Primary VPC
st_region: "UK South"
#specify the address space to be used for the VPC
st_azure_vpc_address_space_create: "172.65.24.0/21"
#CIDR Ranges to be added
st_azure_vpc_address_space_update: "172.64.0.0/20,172.64.16.0/22,172.64.20.0/23,172.64.20.0/23,172.79.0.0/28"
st_public_subnet: "172.64.16.0/25"
st_customer_subnet: "172.64.0.0/22"
st_management_subnet: "172.65.24.0/23"
st_gateway_subnet: "172.79.0.0/28"
#this is the management dns
st_management_dns: proto.azure.paas4sap.svcs.entsvcs.com
#this is the customer dns
st_customer_dns: proto-customer.paas4sap.svcs.entsvcs.com
st_management_reverse_dns: 24.65.172.in-addr.arpa
st_customer_reverse_dns: 0.64.172.in-addr.arpa

#Name to be given to the availability set
availability_set_name: "P4S-Prototype-AS"

#DR
#the DR resource group in which the build will reside
dr_resource_group: "P4S-Prototype-AutomationDR"
#Name to be given to DR VPC
dr_virtual_network_name: "VNET-ESO4SAP3-azureProtoDR"
#Region for DR to be build, note this should be in a seperate region from the primary VPC. Also, the image for VM's are specific to each region so ensure they are correct for the desired regions.
dr_region: "UK South"
#specify the address space to be used for the DR VPC
dr_azure_vpc_address_space_create: "100.65.24.0/21"
#CIDR Ranges to be added
dr_azure_vpc_address_space_update: "100.64.0.0/20,100.64.16.0/22,100.64.20.0/23,100.64.20.0/23,100.79.0.0/28"
dr_public_subnet: "100.64.16.0/25"
dr_customer_subnet: "100.64.0.0/22"
dr_management_subnet: "100.65.24.0/23"
dr_gateway_subnet: "100.79.0.0/28"
dr_customer_reverse_dns: 0.64.100.in-addr.arpa
dr_management_reverse_dns: 24.65.100.in-addr.arpa
  
#FDE
#VM type/size
fde_size: "Standard_B4ms"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
fde_image_offer: "SLES-Standard"
#the OS to be used
fde_publisher: "SUSE"
fde_sku: "12-SP4"

#SAPRouter
#VM type/size
saprouter_size: "Standard_B4ms"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
saprouter_image_offer: "SLES-Standard"
#the OS to be used
saprouter_publisher: "SUSE"
saprouter_sku: "12-SP4"

#MidServers
#VM type/size
mids_size: "Standard_B2s"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
mids_image_offer: "RHEL"
#the OS to be used
mids_publisher: "RedHat"
mids_sku: "7-RAW"

#BUaaS
#VM type/size
cloudboost_size: "Standard_D8_v3"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
cloudboost_image_offer: "SLES-Standard"
#the OS to be used
cloudboost_publisher: "SUSE"
cloudboost_sku: "12-SP4"

#VM type/size
networker_size: "Standard_A8_v2"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
networker_image_offer: "RHEL"
#the OS to be used
networker_publisher: "RedHat"
networker_sku: "7-RAW"

#VM type/size
nmc_size: "Standard_A2_v2"
#the image for VM's are specific to each region so ensure they are correct for the desired regions
nmc_image_offer: "RHEL"
#the OS to be used
nmc_publisher: "RedHat"
nmc_sku: "7-RAW"
