#Create a storage account when suma is true in azure group vars 
- name: create an account
  azure_rm_storageaccount:
    resource_group:  "{{ azure_vm_resource_group }}"
    name: "{{ storage_account_name }}"
    type: Standard_LRS

#Create a container in storage account for store osdisk and data disk
- name: create container
  azure_rm_storageblob:
    resource_group:  "{{ azure_vm_resource_group }}"
    storage_account_name: "{{ storage_account_name }}"
    container: "{{storage_container_name}}"
    state: present
    
#Provisioning a VM with one NIC, dependant on the output of the NIC creation
- name: Provision virtual machine with 1 nic
  azure_rm_virtualmachine:
    name: "{{ azure_vm_name }}"
    resource_group: "{{azure_vm_resource_group}}"
    vm_size: "{{azure_vm_size}}"
    network_interface_names: 
    - "{{nic1.state.name}}"
    image:
      offer: "{{azure_vm_image_offer}}"
      publisher: "{{azure_vm_publisher}}"
      sku: "{{azure_vm_sku}}"
      version: latest
    storage_container_name: "{{storage_container_name}}"
    storage_account_name: "{{storage_account_name}}"
    storage_blob: "{{storage_blob}}"
    data_disks: 
    - lun: 0
      disk_size_gb: "{{data_disk_size}}"
      storage_container_name: "{{storage_container_name}}"
      storage_blob_name: "{{storage_blob_name }}"
      storage_account_name: "{{storage_account_name}}"
      
    admin_username: "{{ username }}"
    ssh_password_enabled: false  
    ssh_public_keys:
      - path: /home/{{ username }}/.ssh/authorized_keys
        key_data: "{{azure_vm_public_ssh}}"
    tags: 
     "{'type' : '{{ azure_vm_tags }}'}"
    state: present
