---
- name: Get facts for one resource group
  azure_rm_virtualmachine_facts:
    resource_group: "{{ rg }}"
  register: vms

- set_fact:
    resource_group: "{{ rg }}"
    alwayson_names: []
    scheduled_names: []

- set_fact:
    alwayson_names: "{{ item.virtual_machines }}"
  when: item.resource_group == resource_group
  with_items: "{{ alwayson }}"

- set_fact:
    scheduled_names: "{{ item.virtual_machines }}"
  when: item.resource_group == resource_group
  with_items: "{{ scheduled }}"

- include: add_to_list.yml
  vars:
    machine_name: "{{ vm.name }}"
    machine_rg: "{{ resource_group }}"
  with_items: "{{ vms.vms }}"
  loop_control:
    loop_var: vm
