- name: "Get difference from two files"
#  gather_facts: no
  shell: diff approved.txt alwayson.txt | grep "^<" > diff-initial.txt && awk -F ' ' '{print $2}' diff-initial.txt > compared.txt 
  args:
    chdir: /home/sureshpavalure/github/SystemTeam/roles/aws-startstop/files

- name: "read a file and store value into variable"
  set_fact:
    file1:  "{{ lookup('file', '/home/sureshpavalure/github/SystemTeam/roles/aws-startstop/files/compared.txt').splitlines() }}"

- name: ec2 remote facts
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      instance-id: "{{ item }}"
  register: ec2facts
  with_items: "{{ file1 }}"

- name: debug facts for an instance
  debug:
    var: ec2facts['instances']['private_ip_address']

  


#- name: list of ec2-remote-facts
#  debug: 
#    msg: "Ip Address: {{ item.instance.image_id }}"
#  with_item: "{{ eni.results }}"

#- name: find ip address
#  debug:
#    msg: "{{ eni.results.instance.private_ip_address }}"

#- name: Add IP to IP group
#  add_host:
#    name: "{{ eni.results.instances }}"
#    groups: IPAdress
#  register: ipad 
 #     with_items: "{{ file1 }}"

#- name: list the ipaddress
#  debug:
#    msg: "{{ ipad }}"

#- name: EC2 instance list 
#  ec2_instance_facts:
#    region: "{{ region }}"
# 
#    filters:
#      availability-zone: "{{ region }}"
#      instance-id: "{{ item }}"
#
#  register: eth0
#  with_items: "{{ file1 }}"
#- name: ec2 instance list
#  debug:
#    msg: "{{ eth0 }}"

#- name: EC2 eni instance facts
#  ec2_eni_facts:
#    region: "{{ region }}"
#    filters:
#      availability-zone: "{{ region }}"
#    
#  register: eth1
#  
#  with_items: "{{ file1 }}"
#
#- name: ec2 eni instance facts
#  debug:
#    msg: ["{{ eth1 }}"]
 




    
