---
- include_tasks: start.yml
  when: action == 'start' and (facts.instances[0].state.name | match("running"))
  
- include_tasks: stop.yml
  when: action == 'stop' and (facts.instances[0].state.name | match("running"))


