- name: "read a file and store value into variable"
  set_fact:
     file1:  "{{ lookup('file', '/home/sureshpavalure/github/SystemTeam/roles/aws-startstop/files/approved.txt').splitlines() }}"

- name: EC2 instance stop when we found the instance 
  ec2_instance:
    region: "{{ region }}"
    state: started
    filters:
      instance_id: "{{ item }}"
  register: ec2_instance
  with_items: "{{ file1 }}"

- name: instance list output
  debug:
    msg: "{{ ec2_instance }}"
