

- name: delete suma storage scripts
  file:
    path: /usr/bin/suma-storage
    state: absent

- name: copy suma-storage
  copy:
    src: files/suma-storage
    dest: /usr/bin/suma-storage
    owner: root
    group: root
    mode: 0755

- name: disk partition and mount
  command: /usr/bin/suma-storage /dev/nvme2n1
  ignore_errors: yes

## the lines below will add the contents of 'line' to the end of the file and pull fstab from the playbook
- name: modify fstab
  lineinfile:
    path: /etc/fstab
    line: '{{ fstab }}'
  ignore_errors: yes

#the skip below didnt work so commented out for testing purposes
#- name: check mkswap exists
#  stat:
#    path: /dev/nvme1n1
#  register: st

- name: makeswap
  command: mkswap /dev/nvme1n1
#  when: st.stat.exists == false
  ignore_errors: yes

- name: swapon
  command: swapon /dev/nvme1n1
#  when: st.stat.exists == false 
  ignore_errors: yes

- name: hostname
  command: hostname -F /etc/hostname
