#the lines below register the image to SUSEConnect
- name: SLES 12.4 registration
  command: sudo SUSEConnect -r "{{ SUSEConnect_reg_code }}" -e "{{ Email_address }}"

#the lines below register the image to SUSEManager
- name: SUSE Manager registration
  command: sudo SUSEConnect -p SUSE-Manager-Server/3.2/x86_64 -r "{{ SUSEManager_reg_code }}"

#the lines below update current image to latest available kernel and rpm packages
- zypper:
    name: '*'
    state: latest
 

 

