---
- set_fact:
    rg: "{{ schedule_list.resource_group }}"
  when: cloud == 'Azure'

- name: Get facts for "{{ schedule_list.resource_group }}"
  azure_rm_resourcegroup_facts:
    name: "{{ schedule_list.resource_group }}"
  register: rg_info
  when: cloud == 'Azure'

- include_tasks: azure.yml
  vars:
    machine_rg: "{{ rg }}"
    machine: "{{ item.name }}"
  with_items: "{{ schedule_list.virtual_machines }}"
  when: cloud == 'Azure' and rg_info.ansible_facts.azure_resourcegroups != []

- set_fact:
    aws_region: "{{ schedule_list.region }}"
  when: cloud == 'AWS'

- name: Get facts for "{{ schedule_list.region }}"
  ec2_instance_facts:
    region: "{{ schedule_list.region }}"
  register: region_instances
  when: cloud == 'AWS'

- include_tasks: aws.yml
  vars:
    instance_id: "{{ item.id }}"
    instance_region: "{{ aws_region }}"
  with_items: "{{ schedule_list.instances }}"
  when: cloud == 'AWS' and region_instances.instances != []
