---

- name: AWS Teardown
  hosts: localhost
  tasks:
    - name: Call Teardown Role
      include_role:
        name: aws-teardown
        
#- name: AWS DR Teardown
#  hosts: localhost
#  tasks:
#    - name: Call Teardown Role
#      include_role:
#        name: aws-teardown
#      vars:
#        vpc: vpc-0fee2cc1e99a93569
#        region: us-east-2
#        list: true
#        terminate: true
#        requester: false
