---
- name: Test AWS Management Creation
  hosts: localhost
  tasks:
    - name: Create VPC
      include_role:
        name: aws-management-vpc
      vars:
        aws_management_vpc_cidr: 10.4.0.0/22, 10.208.0.0/26
        aws_management_vpc_env_name: "Development"
        aws_management_vpc_env_shortname: "Dev"
        aws_management_vpc_region: us-east-1
        aws_management_vpc_public_subnet: 10.4.1.64/26
        aws_management_vpc_private_subnet: 10.4.0.0/24
        aws_management_vpc_private_subnet2: 10.4.3.0/24
        aws_management_vpc_dxc_private_subnet: 10.208.0.0/27
        aws_management_vpc_dxc_private_subnet2: 10.208.0.32/27        
        
