---
- name: compare
  hosts: localhost  
  tasks:
    - name: Call compare the 2 text files     
      include_role:
        name: aws-startstop
        tasks_from: compare.yml

#- name: stop instance
#  hosts: localhost
#  vars:
#    region: us-east-1
#    compared: false
#  tasks:
#    - name: stop instance when compared list is set to true
#      include_role: 
#         name: aws-startstop
#         tasks_from: stop.yml
#      when: compared

#- name: start instance
#  hosts: localhost
#  vars:
#    region: us-east-1
#    approved: false
#  tasks:
#    - name: start instance when approved list is set to true
#      include_role:
#        name: aws-startstop
#        tasks_from: start.yml
#      when: approved

