---
- name: AWS Teardown
  hosts: localhost
  tasks:
    - name: Call Teardown Role
      include_role:
        name: aws-teardown
  
    - pause:
        minutes: 10

    - name: Call The VPC Teardown Role
      include_role:
        name: vpc-teardown
      vars:
        vpc: "{{ st_vpc_id }}"
        vpc_name: "{{ st_vpc_name }}"
        region: "{{ st_region }}"
        list: "{{ st_list }}"
        terminate: "{{ st_terminate }}"
        requester: "{{ st_requester }}"

    - pause:
        minutes: 10

    - name: Call The VPC Teardown Role for DR
      include_role:
        name: vpc-teardown
      vars:
        vpc: "{{ dr_vpc_id }}"
        vpc_name: "{{ dr_vpc_name }}"
        region: "{{ dr_region }}"
        list: "{{ dr_list }}"
        terminate: "{{ dr_terminate }}"
        requester: "{{ dr_requester }}"
      when: dr == 'true'
