---
- name: Gather Hosts for Shutdown
  hosts: localhost
  vars:
    mode: 'stop'
    power_list: []
  tasks:
    - name: Read in exceptions
      set_fact:
        schedule_json: "{{ lookup('file',schedule) | from_json }}"

    - include_role:
        name: add_hosts
      vars:
        cloud: 'AWS'
        action: "{{ mode }}"
        schedule_list: "{{ item }}"
      with_items: "{{ schedule_json.entries }}"

    - debug: var=groups.sap_list

#- name: Start/Stop SAP Service
#  hosts: instances
#  become: yes
#  tasks:
#    - name: Call Start Stop
#      include_role:
#        name: sap-startstop
#      vars:
#        action: stop
               
#- name: Run Start/Stop Instances
#  hosts: localhost
#  tasks:
#   - name: Start/Stop Instance
#     include_role:
#       name: aws-startstop
#     vars:
#       action: stop
#       aws_region: us-east-1
  

