- name: Azure Compartment Configuration
  hosts: localhost
  tasks:
    - name: Create Infastructure
      include_role: 
        name: azure-compartment-config
      vars:
        azure_resource_group: "P4S-Prototype-Automation9" 
        azure_env_name: "VNET-ESO4SAP3-azureProto9"
        azure_region: "UK South"
        azure_vpc_address_space2: "100.64.0.0/20,100.64.16.0/22,100.64.20.0/23,100.64.20.0/23,100.79.0.0/28"
        azure_vpc_address_space: 100.65.24.0/21
        public_subnet: 100.64.16.0/25
        customer_subnet: 100.64.0.0/22
        management_subnet: 100.65.24.0/23
        gateway_subnet: 100.79.0.0/28
        dr_compartment: no
        dns_name_space: "124.in-addr.arpa"
        dns_customer_name: "proto-customer.dxc.paas4sap.svcs.entsvcs.com"
        dns_management_name: "proto.azure.paas4sap.svcs.entsvcs"