# #This creates the Infrastructure
# - name: Azure Compartment Configuration
#   vars_files:
#       - group_vars/azure_cust.yml
#   hosts: localhost
#   tasks:
#     - name: Create Infastructure
#       include_role: 
#         name: azure-compartment-config
#       vars:
#         resource_group: "{{ st_resource_group }}"
#         virtual_network_name: "{{ st_virtual_network_name }}"
#         region: "{{ st_region }}"
#         azure_vpc_address_space_create: "{{ st_azure_vpc_address_space_create }}"
#         azure_vpc_address_space_update: "{{ st_azure_vpc_address_space_update }}"
#         public_subnet: "{{ st_public_subnet }}"
#         customer_subnet: "{{ st_customer_subnet }}"
#         management_subnet: "{{ st_management_subnet }}"
#         gateway_subnet: "{{ st_gateway_subnet }}"
#         management_dns: "{{ st_management_dns }}"
#         customer_dns: "{{ st_customer_dns }}"
#         management_reverse_dns: "{{ st_management_reverse_dns }}"
#         customer_reverse_dns: "{{ st_customer_reverse_dns }}"
#         nsg_resource_group: ""

# #Create SIEM servers        
# - name: Provision Component VMs
#   vars_files:
#       - group_vars/azure_cust.yml 
#   hosts: localhost 
#   tasks:
#     - name: Provision siem server
#       include_role:
#         name: azure-vm
#       vars:
#         azure_vm_name: "siem"
#         azure_vm_resource_group: "{{ st_resource_group }}"
#         region: "{{ st_region }}"
#         azure_vm_dns_resource_group: "{{ st_resource_group }}"
#         azure_vm_vnet: "{{ st_virtual_network_name }}" 
#         azure_vm_size: "{{ siem_size }}"
#         azure_vm_image_offer: "{{ siem_image_offer }}"
#         azure_vm_publisher: "{{ siem_publisher }}"
#         azure_vm_sku: "{{ siem_sku }}"
#         azure_vm_public_ssh: "{{vm_public_keys}}"
#         azure_vm_nic1_subnet: "Management"
#         azure_vm_nic2_subnet: ""
#         azure_vm_nic1_nsg: "nsg-mgmt"
#         azure_vm_nic2_nsg: ""
#         azure_vm_nic1_dns: "{{ st_management_dns }}"
#         azure_vm_nic2_dns: ""
#         azure_vm_nic1_reverse_dns: "{{ st_management_reverse_dns }}"
#         azure_vm_nic2_reverse_dns: ""
#         azure_vm_add_dns: true
#       when: siem

#     - name: Create a network interface with minimal parameters
#       azure_rm_networkinterface:
#         name: siem-nic1
#         resource_group: "{{ st_resource_group }}"
#         virtual_network: "{{ st_virtual_network_name }}"
#         subnet_name: "Management"
#         ip_configurations:
#           - name: default
#             application_security_groups:
#               - asg-mgmt
    
#     - name: install log analytics monitor
#       azure_rm_virtualmachineextension:
#         state: present
#         type_handler_version: "1.7"
#         name: oms-agent
#         location: "{{ st_region }}"
#         resource_group: "{{ st_resource_group }}"
#         virtual_machine_name: siem
#         publisher: Microsoft.EnterpriseCloud.Monitoring
#         virtual_machine_extension_type: OmsAgentForLinux
#         settings: '{"workspaceId": "18b78a20-11d6-4c10-bed7-7b5e5e18d4fb"}'
#         protected_settings: '{"workspaceKey": "356y9/Dc+6af1WJluJX3dFg3p2/Txd6o8/v/y7kdP5ntbwlmloQw1FMxWM8ztlu40TO9bTeg0jyTAF8WTKkg6g=="}'

#     - name: Provision suma server
#       include_role:
#         name: azure-vm
#       vars:
#         azure_vm_name: "suma"
#         azure_vm_resource_group: "{{ st_resource_group }}"
#         region: "{{ st_region }}"
#         azure_vm_dns_resource_group: "{{ st_resource_group }}"
#         azure_vm_vnet: "{{ st_virtual_network_name }}" 
#         azure_vm_size: "{{ siem_size }}"
#         azure_vm_image_offer: "{{ suma_image_offer }}"
#         azure_vm_publisher: "{{ suma_publisher }}"
#         azure_vm_sku: "{{ suma_sku }}"
#         azure_vm_public_ssh: "{{vm_public_keys}}"
#         azure_vm_nic1_subnet: "Management"
#         azure_vm_nic2_subnet: ""
#         azure_vm_nic1_nsg: "nsg-mgmt"
#         azure_vm_nic2_nsg: ""
#         azure_vm_nic1_dns: "{{ st_management_dns }}"
#         azure_vm_nic2_dns: ""
#         azure_vm_nic1_reverse_dns: "{{ st_management_reverse_dns }}"
#         azure_vm_nic2_reverse_dns: ""
#         azure_vm_add_dns: true
#       when: suma
#     - name: Create a network interface with minimal parameters
#       azure_rm_networkinterface:
#         name: suma-nic1
#         resource_group: "{{ st_resource_group }}"
#         virtual_network: "{{ st_virtual_network_name }}"
#         subnet_name: "Management"
#         ip_configurations:
#           - name: default
#             application_security_groups:
#               - asg-mgmt

#SUMA configuration ran on SUMA host
- name: SUMA Server Configuration
  hosts: suma
  become: yes
  vars_files:
      - group_vars/azure_cust.yml
  tasks:
    - name: Call SUMA Server Role
      include_role:
        name: SUMA
      vars:
        #This is the registration code for SUSEConnect found in SCC
        SUSEConnect_reg_code: 5490FA1496BF2C
        #This is the email address for main account (System-Team)
        Email_address: e4s-publiccloud_system@dxc.com
        #This is the registration code for SUSE Manager Service found in SCC
        SUSEManager_reg_code: 692572E0C0DAA8
        fstab: /dev/nvme2n1p1 /manager_storage xfs defaults,nofail 0 1
        FQDN: '{{ suma_short }}.{{ st_management_dns }}'
        #IP address of box
        IP: "{{ ansible_default_ipv4.address }}"
        Short_name: '{{ suma_short }}'
