---
- hosts: AutomationEngine
  tasks:

    - name: Check unar is installed
      yum:
        name: unar
        state: present

    - name: Check wget is installed
      yum:
        name: wget
        state: present

    - name: Download AutomationLamaPython package from Artifactory
      shell: |
        wget --user="{{ artifactory_username  }}" --password="{{ artifactory_password }}"  https://artifactory.csc.com/artifactory/P4S-Automation/artifacts/automationlamapython/latest/automationlamapython-latest.rar -P /tmp
      args:
        warn: false
    
    - name: Unrar AutomationLamaPython package to /tmp
      shell: unar /tmp/automationlamapython-latest.rar -o /tmp

    - include_role:
        name: release-automationlamapython
      vars:
        sourcePath: /tmp/automationlamapython-latest

    - name: Remove rar file
      file:
        state: absent
        path: /tmp/automationlamapython-latest.rar

    - name: Remove automationlamapython-latest directory
      file:
        state: absent
        path: /tmp/automationlamapython-latest
