#This relies on the following files paths existing
#/usr/share/e4s/ansibleOLD
#/usr/share/e4s/ansible

#Improve this by adding when statments to the tasks to only run if files/folders exist/do not exist

---
- hosts: localhost
  tasks:

    - name: Check unar is installed
      yum:
        name: unar
        state: present

    - name: Check wget is installed
      yum:
        name: wget
        state: present

    - name: Download AutomationServices repository from Nexus
      shell: |
        wget --user="{{ nexus_username  }}" --password="{{ nexus_password }}" http://nexus.solutionplace.svcs.hpe.com:8081/nexus/service/local/repositories/spp/content/artifacts/automationservices/latest/automationservices-latest.rar -P /tmp
      args:
        warn: false
    
    - name: Unrar AutomationServices package to /tmp
      shell: unar /tmp/automationservices-latest.rar -o /tmp
    
    - name: Copy to build.artifactstagingdirectory
      shell: cp -R /tmp/automationservices-latest/* {{ working_dir }}

    - name: Remove rar file
      file:
        state: absent
        path: /tmp/automationservices-latest.rar

    - name: Remove automationservices-latest directory
      file:
        state: absent
        path: /tmp/automationservices-latest

