---
- name: SAP Router Configuration
  hosts: saprouter
  tasks:
    - name: Call SAP Router Role
      include_role:
        name: saprouter
      vars: 
        management_subnet_cidr: 10.4.0.0/24
        #This is the Customer Management LAN - AZ1
        acl_localnet_src_a: 172.17.112.0/23
        #This is the Customer Management LAN - AZ2
        acl_localnet_src_b: 172.17.114.0/23
        #This is the command for the desired IP route
        static_route: route add default gw 172.17.112.1 eth1
        azure_region: West US
        aws_media_access_key:  
        aws_media_secret_key:  
