---
- name: VGW
  hosts: localhost
  vars:
    vpc: vpc-0f94eae8635126110
  tasks:
    - name: Locate VGW
      ec2_vpc_vgw_facts:
        region: us-east-1
      register: vgw_facts

    - name: Locate Attached VGW
      set_fact:
        tags: "{{ item.tags }}"
      with_items: "{{ vgw_facts.virtual_gateways }}"
      when: item.vpc_attachments[0].vpc_id == "{{ vpc }}"

    - name: Locate Name
      set_fact:
        vgw_name: "{{ item.value }}"
      with_items: "{{ tags }}"
      when: item.key == "Name"

    - name: Remove VGW
      ec2_vpc_vgw:
        region: us-east-1
        vpc_id: "{{ vpc }}"
        name: "{{ vgw_name }}"
        state: absent
      when: vgw_name is defined 
