- name: AWS Teardown
  hosts: localhost
  vars:
    delete_vpc: false
  tasks:
    - name: Call The VPC Teardown Role for Primary
      include_role:
        name: vpc-teardown
      vars:
        vpc: "{{ st_vpc_id }}"
        vpc_name: "{{ st_vpc_name }}"
        region: "{{ st_region }}"
        list: "{{ st_list }}"
        terminate: "{{ st_terminate }}"
        requester: "{{ st_requester }}"

    - name: Call The VPC Teardown Role for DR
      include_role:
        name: vpc-teardown
      vars:
        vpc: "{{ dr_vpc_id }}"
        vpc_name: "{{ dr_vpc_name }}"
        region: "{{ dr_region }}"
        list: "{{ dr_list }}"
        terminate: "{{ dr_terminate }}"
        requester: "{{ dr_requester }}"
      when: dr

