- name: download cloud watch Agent
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
    dest: /tmp/amazon-cloudwatch-agent.rpm
   

- name: install amazon-cloudwatch-agent.rpm
  yum:
    name: /tmp/amazon-cloudwatch-agent.rpm
    state: present

#check that the /var/log/crowdstrike/falconhoseclient/cs.falconhoseclient.log exists
- name: download cloudwatch config
  aws_s3:
    bucket: siem-config-system-team
    object: /e4s-siem-cloudwatch-config.json
    dest: /tmp/e4s-siem-cloudwatch-config.json
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"

- name: restart cloudwatch with json file
  shell: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/tmp/e4s-siem-cloudwatch-config.json -s "