- name: install PIP
  easy_install:
    name: "pip"
    state: latest

- name: install wget
  yum:
    name: ['wget', 'dos2unix']
    state: present

- name: install boto3 and botocore    
  pip:
    name: ['botocore', 'boto3']
    
- name: download crowdstrike package
  aws_s3:
    bucket: siem-config-system-team
    object: /crowdstrike-siem.rpm
    dest: /tmp/crowdstrike-siem.rpm
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"

- name: installing siem connector
  yum:
    name: /tmp/crowdstrike-siem.rpm
    state: present

- name: download crowdstrike config
  aws_s3:
    bucket: siem-config-system-team
    object: /cs.falconhoseclient.cfg
    dest: /opt/crowdstrike/etc/cs.falconhoseclient.cfg
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"

- name: run dos2unix on config file
  command: dos2unix /opt/crowdstrike/etc/cs.falconhoseclient.cfg

- name: configure siem server
  include_role:
    name: siem
    tasks_from: aws-cloud-watch.yml
  when: aws is defined

- name: start the crowdstrike service
  service:
    name: cs.falconhoseclientd
    state: started 

- name: install policy core utils python
  yum:
    name: policycoreutils-python
    state: present




