- name: create siem server
  ec2:
    image: "{{ aws_ec2_vm_image }}"
    key_name: "064692377866DevCustomerCompartment"
    assign_public_ip: no
    vpc_subnet_id: subnet-5ff18e15
    instance_type: "{{ aws_ec2_vm_instance_type }}"
    instance_profile_name: p4s-iam-role
    region: "{{ aws_region }}"
    group: mgmt-net-all
    exact_count: 1
    count_tag:
      Name: SIEM
    instance_tags:
      Name: SIEM
    wait: yes
  register: siem

- debug:
    msg: "{{ siem }}"

- name: Wait for ssh to come up
  wait_for: host="{{ siem.tagged_instances[0].private_ip }}" port=22 delay=10  timeout=300

# - name: get siem instance facts
#   ec2_instance_facts:
#     filters:
#       "tag:Name": "SIEM"
#       instance-state-name: running
#     region: "{{ aws_region }}"
#   register: siem_facts

- name: add siem server to group list dynamically
  add_host:
    hostname: "{{  siem.tagged_instances[0].private_ip }}"
    groups: "siem"