---
- fail: msg="Bailing out. This role requires the path 'vsts_ssh__private_key'"
  when: vsts_ssh__private_key is undefined

- name: Copy private key
  copy:
    src: "{{ vsts_ssh__private_key }}"
    dest: "~{{ vsts_ssh__user }}/.ssh/{{ vsts_ssh__private_key | basename }}"
    owner: "{{ vsts_ssh__user }}"
    group: "{{ vsts_ssh__user }}"
    mode: 0600
    force: "{{ vsts_ssh__force }}"
  register: copy_result

- name: Add data to SSH config
  blockinfile:
    create: yes
    path: "~{{ vsts_ssh__user }}/.ssh/config"
    owner: "{{ vsts_ssh__user }}"
    group: "{{ vsts_ssh__user }}"
    mode: 0600
    marker: "# {mark} ANSIBLE MANAGED BLOCK: VSTS SSH"
    block: |
      Host vs-ssh.visualstudio.com
          IdentityFile {{ copy_result.dest }}
          IdentitiesOnly true
          {% if vsts_ssh__ssh_user is defined %}User {{ vsts_ssh__ssh_user }}{% endif %}

- name: Add host key to known_hosts
  known_hosts:
    path: "~{{ vsts_ssh__user }}/.ssh/known_hosts"
    name: "vs-ssh.visualstudio.com"
    key: "|1|OiibbQjIMNZLFM22j96C19O6TUQ=|GnWSfxFLCiKijFmmxh82w3PEa3M= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H"