---
#Add NIC 0 Additional Security Groups
- name: Update security groups for eth0
  ec2_eni:
    eni_id: "{{ eth0_id }}"
    region: us-east-1
    security_groups: "{{ aws_eth0_security_groups }}"
    state: present   
#Add NIC 1 Additional Security Groups
- name: Update security groups for eth1
  ec2_eni:
    eni_id: "{{ eth1_id }}"
    region: us-east-1
    security_groups: "{{ aws_eth1_security_groups }}"
    state: present
  when: not single_nic
