# Automating MidServers

- name: create directory
  file:
    path: /servicenow/MidServerA
    state: directory
  become: yes

- name: pull down unzip from snow
  get_url:
    url: https://install.service-now.com/glide/distribution/builds/package/mid/2018/01/03/mid.kingston-10-17-2017__patch1-12-12-2017_01-03-2018_0843.linux.x86-64.zip
    dest: /tmp 
    mode: 0777

- unarchive:
    src: /tmp/mid.kingston-10-17-2017__patch1-12-12-2017_01-03-2018_0843.linux.x86-64.zip
    dest: /servicenow/MidServerA
    remote_src: yes
  become: yes
