---
- name: Check if item exists
  set_fact:
    asg_item: "{{ asg != '' }}"

- name: Create new item for  "{{ asg }}"
  set_fact:
    asg_new_item:
      - { resource_group: "{{ resource_group }}", name: "{{ asg }}" }
  when: asg_item

- name: Add new item to ASG List
  set_fact:
    asgs: "{{ asgs + asg_new_item }}"
  when: asg_item
