---
- include_tasks: start.yml
  vars:
    sys_function: StartSystem
    db_function: StartDatabase   
  when: action == 'start' 

- include_tasks: stop.yml
  vars:
    sys_function: StopSystem
    db_function: StopDatabase
  when: action == 'stop'
