- debug:
    msg: " sybase instance "
 
- name: Sybase - {{ db_function }}
  become: yes
  command: /usr/sap/hostctrl/exe/saphostctrl -function "{{ db_function }}" -dbname "{{  sid_user.stdout_lines[1][:3]|upper }}" -dbtype syb -dbuser sapsa -dbpass "{{ dbpass }}" -force
  with_items: "{{ sid_user.stdout_lines[1] }}"

- name: Sybase - {{ sys_function }}
  become: yes
  command: /usr/sap/hostctrl/exe/sapcontrol -nr 00 -function "{{ sys_function }}"  
  with_items: "{{ sid_user.stdout_lines[1] }}"
