---
- name: Create Resource Group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ region }}"
    state: present

- name: Create Virtual Network
  azure_rm_virtualnetwork: 
    resource_group: "{{ resource_group }}"
    name: "{{ virtual_network_name }}"
    address_prefixes_cidr: "{{ azure_vpc_address_space_create }}"
    state: present

- name: Update Virtual Network
  azure_rm_virtualnetwork: 
    resource_group: "{{ resource_group }}"
    name: "{{ virtual_network_name }}"
    address_prefixes_cidr: "{{ azure_vpc_address_space_update }}"
    state: present

- include_tasks: route-tables.yml

- name: Create asg's and nsg's
  azure_rm_deployment:
    state: present
    resource_group: "{{ resource_group }}"
    location: "{{ region }}"
    template: "{{ lookup('file', 'asg-nsg-config.json' ) }}"

- include_tasks: subnets.yml 

- name: Create Management DNS
  azure_rm_dnszone:
    state: present
    resource_group: "{{ resource_group }}"
    name: "{{ management_dns }}"
  when: management_dns != ""

- name: Create Customer DNS
  azure_rm_dnszone:
    state: present
    resource_group: "{{ resource_group }}"
    name: "{{ customer_dns }}"
  when: customer_dns != ""

- name: Create Managment Reverse DNS
  azure_rm_dnszone:
    state: present
    resource_group: "{{ resource_group }}"
    name: "{{ management_reverse_dns }}"
  when: management_reverse_dns != ""

- name: Create Customer Reverse DNS
  azure_rm_dnszone:
    state: present
    resource_group: "{{ resource_group }}"
    name: "{{ customer_reverse_dns }}"
  when: customer_reverse_dns != ""
