- name: Create Management Route Table
  azure_rm_routetable:
    name: "ManagementRouteTable"
    resource_group: "{{ resource_group }}"
#this will ignore the BGP route if set to yes
    disable_bgp_route_propagation: no
    state: present

- name: Create Public Route Table
  azure_rm_routetable:
    name: "PublicRouteTable"
    resource_group: "{{ resource_group }}"
    disable_bgp_route_propagation: no
    state: present

- name: Create Customer Route Table
  azure_rm_routetable:
    name: "CustomerRouteTable"
    resource_group: "{{ resource_group }}"
    disable_bgp_route_propagation: no
    state: present
