---

- name: Create a CSR function stack, pass in the template via an URL
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ vpc_region }}"
    disable_rollback: true
    template_url: https://s3.amazonaws.com/solutions-reference/transit-vpc/latest/transit-vpc-second-account.template
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
    template_parameters:
      BucketName: "{{ bucket_name }}"
      BucketPrefix: vpnconfigs/
    tags:
      Stack: ansible-cloudformation

- name: Get vpc facts to retreive vpc_id
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{ vpc_env_name }}"
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
    region: "{{ vpc_region }}"
  register: vpc

- debug: var=vpc.vpcs[0].vpc_id
  register: vpc_id_value

- debug: var=vpc_id_value

#Create a new virtual private gateway with the tag for the DEV csr
- name: Create a new unattached vgw for DEV
  ec2_vpc_vgw:
     state: present
     asn: 64513
     region: "{{ vpc_region }}"
     name: "{{ vgw_name }}"
     type: ipsec.1
     vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
     tags:
       owner: "{{ vgw_owner }}"
       transitvpc:spoke: 'true'
     aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
     aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
  register: vgw
  when: csr_tag == 'dev'

#Create a new virtual private gateway with the tag for the TEST csr
- name: Create a new unattached vgw for TEST
  ec2_vpc_vgw:
     state: present
     asn: 64513
     region: "{{ vpc_region }}"
     name: "{{ vgw_name }}"
     type: ipsec.1
     vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
     tags:
       owner: "{{ vgw_owner }}"
       transitvpc:spoke: 'true'
     aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
     aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
  register: vgw
  when: csr_tag == 'test'

#Create a new virtual private gateway with the tag for the PROD csr
- name: Create a new unattached vgw for PROD
  ec2_vpc_vgw:
     state: present
     asn: 64513
     region: "{{ vpc_region }}"
     name: "{{ vgw_name }}"
     type: ipsec.1
     vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
     tags:
       owner: "{{ vgw_owner }}"
       transitvpc:devtest2: 'true'
     aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
     aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
  register: vgw
  when: csr_tag == 'prod'

- debug: var=vgw

- debug: var=az1ngw
- debug: var=az1_nat_gateway.nat_gateway_id

- ec2_vpc_route_table:
    vpc_id: "{{ vgw.vgw.vpc_id }}"
    region: "{{ vpc_region }}"
    tags:
      Name: Management AZ1
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ az1_nat_gateway.nat_gateway_id }}"
    propagating_vgw_ids: "{{ vgw.vgw.id }}"

- pause:
    minutes: 8
