- ec2_instance_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc }}"
  register: ec2_machines

- debug:
    msg: "{{ item_id.instance_id }}" 
  with_items: "{{ ec2_machines.instances }}"
  loop_control:
       loop_var: item_id
  when: list
       
- ec2:
    state: 'absent'
    instance_ids: '{{ item_id.instance_id }}'
    region: "{{ region }}"
  with_items: "{{ ec2_machines.instances }}"
  loop_control:
       loop_var: item_id
  when: terminate

- pause:
    seconds: 30
  when: terminate 
       
- ec2_eni_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc }}"
  register: net_interfaces
  
- debug:
    msg: "{{ item_id.id }}" 
  with_items: "{{ net_interfaces.network_interfaces }}"
  loop_control:
       loop_var: item_id
  when: list
       
- ec2_eni:
    region: "{{ region }}"
    eni_id: "{{ item_id.id }}"
    force_detach: yes
    state: absent
  with_items: "{{ net_interfaces.network_interfaces }}"
  loop_control:
       loop_var: item_id
  when: terminate
