---

- include: vpc.yml
  vars:
    vpc: "{{ dr_vpc_id }}"
    vpc_name: "{{ dr_vpc_name }}"
    region: "{{ dr_region }}"
    list: "{{ dr_list }}"
    terminate: "{{ dr_terminate }}"
    requester: "{{ dr_requester }}"
  when: dr == 'true'

