#Tear down the non-dr customer build
- include: non-dr.yml
  vars:
    requester: true

#Run the teardown a second time for DR
- include: dr.yml
  vars:
    vpc: "{{ dr_vpc }}"
    vpc_name: "{{ dr_vpc_name }}"
    region: "{{ dr_region }}"
    list: "{{ dr_list }}"
    terminate: "{{ dr_terminate }}"
    requester: false
  when: dr == true

