---

#Remove the VPC
#- include: vpc.yml
#  vars:
#    vpc: "{{ st_vpc_id }}"
#    vpc_name: "{{ st_vpc_name }}"
#    region: "{{ st_region }}"
#    list: "{{ st_list }}"
#    terminate: "{{ st_terminate }}"
#    requester: "{{ st_requester }}"


- include: vpc.yml
  vars:
    vpc: "{{ dr_vpc_id }}"
    vpc_name: "{{ dr_vpc_name }}"
    region: "{{ dr_region }}"
    list: "{{ dr_list }}"
    terminate: "{{ dr_terminate }}"
    requester: "{{ dr_requester }}"
  when: dr == 'true'

#Remove the Route53 DNS entries
- include: route53.yml
  vars:
    vpc: "{{ st_vpc_id }}"
    vpc_name: "{{ st_vpc_name }}"
    region: "{{ st_region }}"
    list: "{{ st_list }}"
    terminate: "{{ st_terminate }}"
    requester: "{{ st_requester }}"
  with_dict: "{{ route53_zones }}"

