---
#Remove A records and zone for zone 1
- name: List "{{ item.key }}" records in hosted zone
  route53_facts:
    query: record_sets
    hosted_zone_id: "{{ item.value }}"
  register: records

#Set Zone Name
- name: Set Zone Name
  set_fact:
    zone_name: "{{ item.key }}"

#List type A records from given zone
- name: Get the A records from "{{ item.key }}"
  route53:
      state: get
      zone: "{{ zone_name }}"
      record: "{{ item.Name }}"
      type: A
      private_zone: True
  with_items: "{{ records.ResourceRecordSets }}"

#Remove type A records from given zone
- name: Remove A records for "{{ zone_name }}"
  route53:
    state: delete
    zone: "{{ zone_name }}"
    record: "{{ item.Name }}"
    type: A
    value: "{{ item.ResourceRecords[0].Value }}"
    ttl: "{{ item.TTL }}"
    private_zone: True
  with_items: "{{ records.ResourceRecordSets }}"
  when: terminate

#List PTR type records from given zone
- name: Get the PTR records from "{{ zone_name }}"
  route53:
      state: get
      zone: "{{ zone_name }}"
      record: "{{ item.Name }}"
      type: PTR
      private_zone: True
  with_items: "{{ records.ResourceRecordSets }}"

#Remove PTR type records from given zone
- name: Remove PTR records for "{{ zone_name }}"
  route53:
    state: delete
    zone: "{{ zone_name }}"
    record: "{{ item.Name }}"
    type: PTR
    value: "{{ item.ResourceRecords[0].Value }}"
    ttl: "{{ item.TTL }}"
    private_zone: True
  with_items: "{{ records.ResourceRecordSets }}"
  when: terminate

#Remove given hosted zone
- name: Remove "{{ zone_name }}" from route53
  route53_zone:
    zone: "{{ zone_name }}"
    vpc_id: "{{ vpc }}"
    vpc_region: "{{ region }}"
    state: absent
  when: terminate

