- ec2_vpc_subnet_facts:
    filters:
      vpc-id: "{{ vpc }}"
  register: subnets

- ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ vpc }}"
    cidr: "{{ item.cidr_block }}"
  with_items: "{{ subnets.subnets }}"
  when: 
    - item.vpc_id == "{{ vpc }}"
    - terminate

- ec2_group_facts:
    filters:
      vpc-id: "{{ vpc }}"
  register: security_groups

- ec2_group:
    state: absent
    group_id: "{{ item.group_id }}"
  with_items: "{{ security_groups.security_groups }}"
  ignore_errors: yes
  when: terminate

- name: Get All NACLs
  register: all_nacls
  ec2_vpc_nacl_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc }}"

- name: Delete nacl
  ec2_vpc_nacl:
    nacl_id: "{{ item.nacl_id }}"
    state: absent
  with_items: "{{ all_nacls.nacls }}"
  ignore_errors: yes
  when: terminate

- ec2_vpc_igw:
    vpc_id: "{{ vpc }}"
    region: "{{ region }}"
    state: absent
  when: terminate

- name: Get facts on the route tables in the VPC
  ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc }}"
  register: route_tables

- name: Remove the route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc }}"
    region: "{{ region }}"
    route_table_id: "{{ item.id }}"
    state: absent
    lookup: id
  with_items: "{{ route_tables.route_tables }}"
  ignore_errors: yes
  when: terminate

- name: Find VGWs for Region
  ec2_vpc_vgw_facts:
    region: "{{ region }}"
  register: vgw_facts

- name: Gather facts about vpn connections
  ec2_vpc_vpn_facts:
    filters:
      vpn-gateway-id: "{{ gateway_id }}"
  register: connections

- debug: var=connections

- name: Remove all VPN connections for a VGW
  ec2_vpc_vpn:
    state: absent
    vpn_connection_id: "{{ item.vpn_connection_id }}"
  with_items: "{{ connections.vpn_connections }}"

- name: Remove tag from virtual private gateway
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ gateway_id }}"
    state: absent
    tags:
      Name: cv-csr-vgw
      owner: System Team
      transitvpc:spoke: 'true'

- pause:
    minutes: 1

- name: Remove VGW
  ec2_vpc_vgw:
    region: "{{ region }}"
    vpc_id: "{{ vpc }}"
    vpn_gateway_id: "{{ gateway_id }}"
    state: absent
    wait_timeout: 320
  when:
    - terminate

- pause:
    minutes: 1

- ec2_vpc_net_facts:
    vpc_ids: "{{ vpc }}"
  register: vpc_facts


- name: Remove the VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    state: absent
    region: "{{ region }}"
    cidr_block: "{{ item.cidr_block }}"
    purge_cidrs: yes
    tags:
       Name: "{{ vpc_name }}"
  with_items: "{{ vpc_facts.vpcs }}"
  when: terminate
