#Get VPC facts
- ec2_vpc_net_facts:
    vpc_ids: "{{ vpc }}"
    region: "{{ region }}"
  register: vpc_facts

#Remove the VPC
- name: Remove the VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    state: absent
    region: "{{ region }}"
    cidr_block: "{{ item.cidr_block }}"
    purge_cidrs: yes
    tags:
       Name: "{{ vpc_name }}"
  with_items: "{{ vpc_facts.vpcs }}"
  retries: 3
  delay: 5
  when: terminate
