---
- set_fact:
    list: []

- include: create_rules.yml
  vars:
    rule_protocol: "{{ item.protocol }}"
    rule_ports: "{{ item.ports }}"
    rule_cidr_ip: "{{ item.cidr_ip }}"
    rule_group_name: "{{ item.group_name }}"
  with_items: "{{ sgtest.rules }}"

- ec2_group:
    name: "{{ sgtest.name }}"
    description: "{{ sgtest.description }}"
    vpc_id: "{{ vpc }}"
    region: "{{ region }}"
    tags:
      Name: "{{ sgtest.name }}"
    rules: "{{ list }}"
