---
#Create Customer Route Table
- ec2_vpc_route_table:
    vpc_id: "{{ customer_network.vpc.id  }}"
    region: "{{ aws_customer_vpc_region  }}"
    tags:
      Name: Customer
    subnets:
      - "{{ customeraz1.subnet.id }}"
  register: customer_route_table
#Create Public Route Table
- ec2_vpc_route_table:
    vpc_id: "{{ customer_network.vpc.id  }}"
    region: "{{ aws_customer_vpc_region  }}"
    tags:
      Name: Public
    subnets:
      - "{{ publicaz1.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
  register: public_route_table
#Create Management Route Table
- ec2_vpc_route_table:
    vpc_id: "{{ customer_network.vpc.id  }}"
    region: "{{ aws_customer_vpc_region  }}"
    tags:
      Name: Management AZ1
    subnets:
      - "{{ managementaz1.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ az1_nat_gateway.nat_gateway_id }}"
  register: managementaz1_route_table
