- ec2_group:
    name: SAP-mgt
    description: The interfaces of any SAP servers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: SAP-mgt
    rules:
      - proto: tcp
        ports: 3900 - 3999
        group_name: SAP-mgt
      - proto: tcp
        ports: 1128
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 50013 - 59914
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3600 - 3699
        group_name: SAP-mgt
      - proto: tcp
        ports: 3260
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 2049
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 1129
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3200-3299
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
  register: SAP_mgt

- ec2_group:
    name: buaas-mgt
    description: The interfaces of any BUaaS servers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: buaas-mgt
    rules:
      - proto: tcp
        ports: 3741
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 9002
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 7937 - 9936
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
  register: buaas_mgt

- ec2_group:
    name: saprtr-pub
    description: The interfaces of any SAP routers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: saprtr-pub
    rules:
      - proto: tcp
        ports: 3299
        cidr_ip: 0.0.0.0/0
  register: saprtr_pub

- ec2_group:
    name: cust-net-all
    description: Every AWS interface in the VPCs AZ1 2 3 customer networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: cust-net-all
    rules:
      - proto: -1
        ports: 0
        group_name: cust-net-all
      - proto: tcp
        ports: 3299
        group_name: saprtr-pub
      - proto: tcp
        ports: 3298
        group_name: saprtr-pub
  register: cust_net_all

- ec2_group:
    name: hrs-sid-cst
    description: The interfaces of any HRS-SID servers on any customer networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: hrs-sid-cst
  register: hrs_sid_cst

- ec2_group:
    name: hrs-sid-mgt
    description: The interfaces of any HRS-SID servers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: hrs-sid-mgt
  register: hrs_sid_mgt

- ec2_group:
    name: mgmt-net-all
    description: Every AWS interface in the VPCs AZ1 2 3 management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: mgmt-net-all
    rules:
      - proto: -1
        ports: 0
        group_name: mgmt-net-all
      - proto: -1
        ports: 0
        cidr_ip: 100.64.0.0/12
      - proto: tcp
        ports: 22
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3389
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3389
        cidr_ip: 10.208.0.0/27
      - proto: tcp
        ports: 3389 
        cidr_ip: 10.208.0.64/27 
      - proto: tcp
        ports: 8080
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: icmp
        ports: -1
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 873
        cidr_ip: 100.64.0.0/12
  register: mgmt_net_all

- ec2_group:
    name: mid-mgt
    description: The interfaces of any MID servers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: mid-mgt
  register: mid_mgt

- ec2_group:
    name: proxy-dns-cst
    description: The interfaces of any proxy/DNS servers on any customer networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: proxy-dns-cst
    rules:
      - proto: tcp
        ports: 3128
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports: 53
        cidr_ip: 0.0.0.0/0
      - proto: udp
        ports: 53
        cidr_ip: 0.0.0.0/0
      - proto: TCP
        ports: 50013
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
  register: proxy_dns_cst

- ec2_group:
    name: proxy-dns-mgt
    description: The interfaces of any proxy/DNS servers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: proxy-dns-mgt
    rules:
      - proto: tcp
        ports: 1128
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3299
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 3128
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: udp
        ports: 53
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 53
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 1129
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
      - proto: tcp
        ports: 50013
        cidr_ip: "{{ aws_customer_vpc_management_cidr  }}"
  register: proxy_dns_mgt

- ec2_group:
    name: pub-net-all
    description: Every AWS interface in the VPCs AZ1 2 3 public networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: pub-net-all
    rules:
      - proto: -1
        ports: 0
        group_name: pub-net-all
  register: pub_net_all

- ec2_group:
    name: saprtr-mgt
    description: The interfaces of any SAP routers on any management networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: saprtr-mgt
    rules:
      - proto: tcp
        ports: 8080
        group_name: mgmt-net-all
      - proto: tcp
        ports: 8081
        group_name: mgmt-net-all
  register: saprtr_mgt

- ec2_group:
    name: SAP-cst
    description: The interfaces of any SAP servers on any customer networks must be assigned to this security group
    vpc_id: "{{ sgvpcid }}"
    region: "{{ aws_customer_vpc_region }}"
    tags:
      Name: SAP-cst
    rules:
      - proto: tcp
        ports: 6001
        group_name: proxy-dns-cst
  register: SAP_cst

- ec2_group:
    name: suma-mgt
    description: The interfaces of any SUMA servers on any management networks must be assigned to this security group
    vpc_id: "{{ customer_network.vpc.id }}"
    region: "{{ aws_customer_vpc_region }}"
    rules:
      -  proto: tcp
         ports: 80
         group_name: mgmt-net-all
      -  proto: tcp
         ports: 5269
         group_name: mgmt-net-all
      -  proto: tcp
         ports: 22
         group_name: mgmt-net-all
      -  proto: tcp
         ports: 5222
         group_name: mgmt-net-all
      -  proto: tcp
         ports: 4505
         group_name: mgmt-net-all
      -  proto: tcp
         ports: 443
         group_name: mgmt-net-all
  register: suma_mgt
