---
- debug: 
    msg: " gather host group "

- ec2_eni_facts:
    filters:
      network-interface-id: "{{machine_interface}}"
  register: interface_facts
  when: (not skip_machine) and (facts.instances[0].tags.SystemId is defined)

- name: Add to group
  add_host:
    name: "{{ interface_facts.network_interfaces[0].private_ip_addresses[0].private_ip_address }}" 
    groups: instances
  when:  (not skip_machine ) and (interface_facts.network_interfaces[0].private_ip_addresses[0].private_ip_address | match("172.17."))

    
