---
- ec2_vpc_route_table:
    vpc_id: "{{ management_network.vpc.id  }}"
    region: "{{ aws_management_vpc_region  }}"
    tags:
      Name: "{{ aws_management_vpc_env_name }} Tools DXC Private"

- ec2_vpc_route_table:
    vpc_id: "{{ management_network.vpc.id  }}"
    region: "{{ aws_management_vpc_region  }}"
    tags:
      Name: "{{ aws_management_vpc_env_name }} Tools Public Subnet"
    subnets:
      - "{{ public.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- ec2_vpc_route_table:
    vpc_id: "{{ management_network.vpc.id  }}"
    region: "{{ aws_management_vpc_region  }}"
    tags:
      Name: "{{ aws_management_vpc_env_name }} Tools Private Subnet"
    subnets:
      - "{{ private.subnet.id }}"
      - "{{ private_2.subnet.id }}"
      - "{{ dxc_private.subnet.id }}"
      - "{{ dxc_private_2.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ nat.nat_gateway_id }}"
