- name: Create sapsys User Group
  group:
    name: sapsys
    system: yes
    state: present

- name: Create sapadm User Group
  user:
    name: sapadm
    group: sapsys

- name: Create Directory Structure for Wilyem
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /media
    - /media/SAP
    - /media/SAP/WILYEM

- name: Zypper install Python Pip
  zypper:
    name: python-pip
    state: present
    disable_gpg_check: yes
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Install botocore
  pip:
    name: botocore
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Install boto3
  pip:
    name: boto3
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Pull WILYEM from Media Bucket (1/3)
  aws_s3:
    bucket: p4s-binaries
    object: /INSTALL_UPGRADE/SAP/WILYEM/ISAGNTJ5STD02_0-70003142.ZIP
    dest: /media/SAP/WILYEM/ISAGNTJ5STD02_0-70003142.ZIP
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Pull WILYEM from Media Bucket (2/3)
  aws_s3:
    bucket: p4s-binaries
    object: /INSTALL_UPGRADE/SAP/WILYEM/WILYISEM02_0-70003060.ZIP
    dest: /media/SAP/WILYEM/WILYISEM02_0-70003060.ZIP
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Pull WILYEM from Media Bucket (3/3)
  aws_s3:
    bucket: p4s-binaries
    object: /INSTALL_UPGRADE/SAP/WILYEM/WILYISMM02_0-70003054.ZIP
    dest: /media/SAP/WILYEM/WILYISMM02_0-70003054.ZIP
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Pull Hostagent from Media Bucket
  aws_s3:
    bucket: p4s-binaries
    object: /INSTALL_UPGRADE/TOOLS/SAPHOSTAGENT37_37-20009394.SAR
    dest: /media/SAP/SAPHOSTAGENT37_37-20009394.SAR
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Pull SAPCAR from Meida Bucket
  aws_s3:
    bucket: p4s-binaries
    object: /INSTALL_UPGRADE/TOOLS/SAPCAR_816-80000935.EXE
    dest: /media/SAP/SAPCAR_816-80000935.EXE
    mode: get
    aws_access_key: "{{ lookup('env','MEDIA_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env','MEDIA_SECRET_KEY') }}"
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Add Execute permissions to SAPCAR
  file:
    path: /media/SAP/SAPCAR_816-80000935.EXE
    mode: 0755

- name: Create directory for SAP Hostagent
  file:
    path: /media/SAP/SAPHOSTAGENT37_37-20009394
    state: directory

- name: Run command to extract Hostagent
  command: "/media/SAP/SAPCAR_816-80000935.EXE -xvf /media/SAP/SAPHOSTAGENT37_37-20009394.SAR"
  args:
    chdir: /media/SAP/SAPHOSTAGENT37_37-20009394

- name: Install Java
  zypper:
    name: java-1_8_0-ibm
    state: present
  environment:
    http_proxy: "http://{{ proxy_domain }}:8080"
    https_proxy: "http://{{ proxy_domain }}:8080"
    no_proxy: "localhost, 127.0.0.1"

- name: Create directory structure for Enterpise Manager
  file:
    path: "{{ item }}" 
    state: directory
  with_items:
    - /usr
    - /usr/sap
    - /usr/sap/ccms
    - /usr/sap/ccms/apmintroscope

- name: Change permissions on Enterpise Manager directory structure
  file:
    path: "{{ item }}"
    owner: sapadm
    group: sapsys
  with_items:
    - /usr/sap/ccms
    - /usr/sap/ccms/apmintroscope


- name: Change Owner on WILYEM directory
  file:
    path: /media/SAP/WILYEM
    owner: sapadm
    group: sapsys

- name: Create WILY extracted directory
  file:
    path: /media/WILY_10_5/extracted
    state: directory

- name: Unarchive WILYEM
  unarchive:
    src: /media/SAP/WILYEM/WILYISEM02_0-70003060.ZIP
    dest: /media/WILY_10_5/extracted/
    remote_src: yes

- name: Change owner of extracted WILYEM
  file:
    path: /media/WILY_10_5/extracted
    owner: sapadm
    group: sapsys
    recurse: yes

- name: Change permissions of WILYEM install file
  file:
    path: /media/WILY_10_5/extracted/introscope10.5.2.27linuxAMD64SAP.bin
    mode: 0755

- name: Accept license
  lineinfile:
    path: /media/WILY_10_5/extracted/ca-eula.txt
    regexp: '^CA-EULA=reject'
    line: 'CA-EULA=accept'

- name: Install WILYEM
  command: /media/WILY_10_5/extracted/introscope10.5.2.27linuxAMD64SAP.bin -Djava.awt.headless=true
  become_user: sapadm
  args:
    creates: /usr/sap/ccms/apmintroscope/install/Introscope_10.5.2.27_InstallLog.log

- name: Extract additional modules
  unarchive:
    src: /media/SAP/WILYEM/WILYISMM02_0-70003054.ZIP
    dest: /usr/sap/ccms/apmintroscope
    remote_src: yes
  become_user: sapadm
  
- name: Change owner on WILYEM directory
  file:
    path: /usr/sap/ccms/apmintroscope
    owner: sapadm
    group: sapsys
        
- name: Start EM
  command: /usr/sap/ccms/apmintroscope/bin/EMCtrl.sh start
  become_user: sapadm
  args:
    chdir: /usr/sap/ccms/apmintroscope/bin/

- name: Modify EM properties
  lineinfile:
    path: /usr/sap/ccms/apmintroscope/config/IntroscopeEnterpriseManager.properties
    regexp: '^#introscope.enterprisemanager.name='
    line: 'introscope.enterprisemanager.name={{ fde_virualhostname }}'

- name: Add EM Service
  copy:
    src: files/EMC.service
    dest: /etc/systemd/system/EMC.service
    owner: root
    group: root
    mode: 0755

- name: Enable EM Service
  systemd:
    name: EMC.service
    state: started
    enabled: yes
 
- name: Start EM Service
  service:
    name: EMC.service
    state: started

- name: Add Auto Start EM
  lineinfile:
    path: /etc/init.d/after.local
    insertafter: EOF
    line: "{{ item }}"
  with_items:
    - cd /usr/sap/ccms/apmintroscope/bin/
    - sudo -u sapadm ./EMCtrl.sh start

- name: Install SAP Hostagent
  command: ./saphostexec -install
  args:
    chdir: /media/SAP/SAPHOSTAGENT37_37-20009394
