#Configure squid proxy for LaMa
#- { include: squid.yml, become: yes }  

#Configure DNS forwarder
#- { include: dnsforwarder.yml, become: yes }

#Configure Enterprise Manager
- { include: enterprisemanager.yml, become: yes }
