---
- zypper_repository:
    repo: 'https://download.opensuse.org/repositories/server:proxy/SLE_12_SP3/server:proxy.repo'
#  environment:
#    http_proxy: "http://{{ proxy_domain }}:8080"
#    https_proxy: "http://{{ proxy_domain }}:8080"
#    no_proxy: "localhost, 127.0.0.1"
  ignore_errors: yes
  become: yes

- name: install squid
  zypper:
    name: squid
    state: present
    disable_gpg_check: yes
  become: yes

- name: copy squid.conf
  copy:
    src: files/squid.conf
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: modify squid.conf - customer_lan
  lineinfile:
    path: /etc/squid/squid.conf
    regexp: '^acl localnet src customer_lan'
    line: 'acl localnet src {{ customer_subnet_cidr }}'
  become: yes

- name: modify squid.conf - customer_management_lan
  lineinfile:
    path: /etc/squid/squid.conf
    regexp: '^acl localnet src customer_management_lan'
    line: 'acl localnet src {{ customer_management_subnet_cidr }}'
  become: yes

- name: modify squid.conf - lama_lan
  lineinfile:
    path: /etc/squid/squid.conf
    regexp: '^acl localnet src lama_lan'
    line: 'acl localnet src {{ lama_ip }}'
  become: yes

- name: restart squid
  service:
    name: squid
    state: restarted
  become: yes

- name: install bind
  zypper:
    name: bind
    state: present
    disable_gpg_check: yes
#  environment:
#    http_proxy: "http://{{ proxy_domain }}:8080"
#    #    https_proxy: "http://{{ proxy_domain }}:8080"
#    #    no_proxy: "localhost, 127.0.0.1"
  become: yes

- name: copy named.conf
  copy:
    src: files/named.conf
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0755
  become: yes

- name: modify named.conf - customer-lan
  lineinfile:
    path: /etc/named.conf
    regexp: '^     customer-lan'
    line: '     {{ customer_lan }};'
  become: yes

- name: modify named.conf - management-lan
  lineinfile:
    path: /etc/named.conf
    regexp: '^     management-lan'
    line: '     {{ management_lan }};'
  become: yes

- name: modify named.conf - dns-dev
  lineinfile:
    path: /etc/named.conf
    regexp: '^     dns-dev'
    line: '     {{ dns_ip_dev }};'
  become: yes

- name: modify named.conf - dns-test
  lineinfile:
    path: /etc/named.conf
    regexp: '^     dns-test'
    line: '     {{ dns_ip_test }};'
  become: yes

- name: modify named.conf - management_zone
  lineinfile:
    path: /etc/named.conf
    regexp: '^zone "management_zone"'
    line: 'zone "{{ management_zone }}" in {'
  become: yes

- name: modify named.conf - customer_zone
  lineinfile:
    path: /etc/named.conf
    regexp: '^zone "customer_zone"'
    line: 'zone "{{ customer_zone }}" in {'
  become: yes

- name: modify named.conf - reverse_zone
  lineinfile:
    path: /etc/named.conf
    regexp: '^zone "reverse_zone"'
    line: 'zone "{{ reverse_zone }}" in {'
  become: yes

- name: modify named.conf - management_forwarders
  lineinfile:
    path: /etc/named.conf
    regexp: '^        forwarders { management_forwarders };'
    line: '        forwarders { {{ management_forwarders }} };'
  become: yes

- name: modify named.conf - customer_forwarders
  lineinfile:
    path: /etc/named.conf
    regexp: '^        forwarders { customer_forwarders };'
    line: '        forwarders { {{ customer_forwarders }} };'
  become: yes

- name: modify named.conf - reverse_forwarders
  lineinfile:
    path: /etc/named.conf
    regexp: '^        forwarders { reverse_forwarders };'
    line: '        forwarders { {{ reverse_forwarders }} };'
  become: yes

- name: copy forwarders.conf
  copy:
    src: files/forwarders.conf
    dest: /etc/named.d/forwarders.conf
    owner: root
    group: named
    mode: 0755
  become: yes

- name: modify forwarders.conf
  lineinfile:
    path: /etc/named.d/forwarders.conf
    regexp: '^        forwarder_ip'
    line: '        {{ forwarder_ip }}'
  become: yes

- name: enable on startup
  shell: chkconfig named on
  become: yes

- name: restart bind service
  shell: rcnamed restart
  become: yes

- name: modify resolv.conf - search
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^search'
    line: 'search {{ fde_customer_domain }}'
  become: yes

- name: modify resolv.conf - nameserver
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver {{ fde_ip }}'
  become: yes
