---
- name: Test AWS Customer Creation
  hosts: localhost
  tasks:
    - name: Create VPC
      include_role:
        name: aws-customer-vpc
      vars:
        aws_customer_vpc_cidr: 172.17.112.0/21, 172.16.0.0/20, 172.16.16.0/22, 172.16.20.0/23
        aws_customer_vpc_env_name: "AlexTest"
        aws_customer_vpc_region: us-east-1
        publicaz1_cidr: 172.16.16.128/25
        publicaz2_cidr: 172.16.16.0/25
        publicaz3_cidr: 172.16.17.0/25
        managementaz1_cidr: 172.17.112.0/23
        managementaz2_cidr: 172.17.114.0/23
        managementaz3_cidr: 172.17.116.0/23
        customeraz1_cidr: 172.16.0.0/22
        customeraz2_cidr: 172.16.4.0/22
        customeraz3_cidr: 172.16.8.0/22
        clusteraz1_cidr: 172.16.18.0/24
        clusteraz2_cidr: 172.16.19.0/24
        clusteraz3_cidr: 172.16.20.0/24
        aws_customer_vpc_management_cidr: 10.2.0.0/22
