- name:
  debug:
    msg: "{{ asgs }}"
    
- name: asg stuff
#Using Paul Thomas's Application Security Groups module to Assign ASG's to a NIC
  azure_rm_networkinterface_asg:
    subscription_id: '{{ lookup("env", "AZURE_SUBSCRIPTION_ID") }}'
    client_id: '{{ lookup("env", "AZURE_CLIENT_ID") }}'
    secret: '{{ lookup("env", "AZURE_SECRET") }}'
    tenant: '{{ lookup("env", "AZURE_TENANT") }}'
    resource_group: "{{ asgs[0].resource_group }}"
    name: "{{ azure_vm_nic }}"
    ip_configurations:
      - name: "default"
        application_security_groups: "{{ asgs }}"
